version: "3"

services:
  server:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      # npl-idea-plugin currently does not use snippets, and ones provided elsewhere are not available when serving locally
      CHECK_SNIPPET_PATHS: false
    stop_signal: SIGKILL

  builder:
    build:
      context: .
    volumes:
      - site-docs:/docs
    environment:
      # npl-idea-plugin currently does not use snippets, and ones provided elsewhere are not available when serving locally
      CHECK_SNIPPET_PATHS: false
    entrypoint: ["mkdocs", "build", "--clean"]

  htmltest:
    image: wjdp/htmltest
    volumes:
      - site-docs:/test
    entrypoint: ["htmltest", "--conf", "/test/htmltest.yml"]
    depends_on:
      builder:
        condition: service_completed_successfully

volumes:
  site-docs:
