FROM ghcr.io/noumenadigital/documentation/mkdocs-builder:latest

RUN rm -rf /docs/content/docs/runtime/tools/build-tools/*
COPY npl-cli/docs/runtime/tools/build-tools /docs/content/docs/runtime/tools/build-tools
