name: "Publish NPL CLI Binaries"

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Override the automatic tag name for the release"
        required: false
        type: string
      release_name:
        description: "Override the automatic name of the release"
        required: false
        type: string

concurrency:
  group: "publish"
  cancel-in-progress: false

jobs:
  determine-version:
    name: "Determine Release Version"
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{ steps.set-version.outputs.version }}
      release_name: "NPL Cli release${{ steps.set-version.outputs.version }}"
      version: ${{ steps.set-version.outputs.version }}
      should_release: ${{ steps.validate-version.outputs.should_release }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Determine Release Version"
        id: set-version
        run: echo "version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT

      - name: "Validate the release version"
        id: validate-release-version
        run: |
          # Run the script and capture its output
          OUTPUT=$(.github/scripts/validate-version.sh)

          # Extract the should_release value and set as output
          SHOULD_RELEASE=$(echo "$OUTPUT" | grep "should_release=" | cut -d= -f2)
          echo "should_release=$SHOULD_RELEASE" >> $GITHUB_OUTPUT

          # Display the full output for debugging
          echo "$OUTPUT"

  build-native:
    name: "Build ${{ matrix.os }}-${{ matrix.arch }} Native Binary"
    needs: determine-version
    if: needs.determine-version.outputs.should_release == 'true'
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu
            runner: ubuntu-latest
            arch: x86_64
            output_name: npl-cli-linux-x86_64-${{needs.determine-version.outputs.version}}
          - os: ubuntu
            runner: linux-arm-64
            arch: aarch64
            output_name: npl-cli-linux-aarch64-${{needs.determine-version.outputs.version}}
          - os: macos
            runner: macos-13
            arch: x86_64
            output_name: npl-cli-macos-x86_64-${{needs.determine-version.outputs.version}}
          - os: macos
            runner: macos-latest
            arch: aarch64
            output_name: npl-cli-macos-aarch64-${{needs.determine-version.outputs.version}}

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Set up Maven"
        uses: actions/setup-java@v4
        with:
          distribution: "graalvm"
          java-version: "21"
          cache: "maven"

      - name: "Build npl-cli native binary"
        run: mvn -Pnative package -DskipTests

      - name: "Prepare binary for upload (Linux/macOS)"
        run: |
          mkdir -p dist
          if [ -f target/npl-cli ]; then
            cp target/npl-cli dist/${{ matrix.output_name }}
            chmod +x dist/${{ matrix.output_name }}
          fi

      - name: "Upload native binary artifact"
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.output_name }}
          path: dist/${{ matrix.output_name }}
          if-no-files-found: error
          retention-days: 30

  create-release:
    name: "Create GitHub Release"
    needs: [determine-version, build-native]
    if: needs.determine-version.outputs.should_release == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: "Download individual artifacts"
        uses: actions/download-artifact@v4
        with:
          path: ./individual-artifacts

      - name: "Create Release"
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ needs.determine-version.outputs.release_tag }}
          name: ${{ needs.determine-version.outputs.release_name }}
          body: "NPL CLI release ${{ needs.determine-version.outputs.release_tag }}"
          commit: ${{ github.sha }}
          draft: ${{ github.event.inputs.draft || false }}
          prerelease: ${{ github.event.inputs.prerelease || false }}
          artifacts: "./individual-artifacts/*/*"
          artifactErrorsFailBuild: true
