name: "Verify and test"
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  validate-config:
    name: "Validate native config diff (${{ matrix.runner }})"
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, linux-arm-64, macos-13, macos-latest]
    runs-on: ${{ matrix.runner }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Set up Maven"
        uses: actions/setup-java@v4
        with:
          distribution: "graalvm"
          java-version: "21"
          cache: "maven"

      - name: "Validate native config diff"
        run: .github/scripts/validate-native-config-files.sh

  build-and-test:
    name: "Build and test native binary (${{ matrix.runner }})"
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, linux-arm-64, macos-13, macos-latest]
    runs-on: ${{ matrix.runner }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Set up Maven"
        uses: actions/setup-java@v4
        with:
          distribution: "graalvm"
          java-version: "21"
          cache: "maven"

      - name: "Build npl-cli native binary and test it"
        run: mvn -Pnative clean verify
