name: "Verify and test"
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    name: "Run tests"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Set up Java and Maven"
        uses: actions/setup-java@v4
        with:
          distribution: "graalvm"
          java-version: "21"
          cache: "maven"

      - name: "Validate native config diff"
        run: .github/scripts/validate-native-config-files.sh

  verify-native:
    name: "Build and verify ${{ matrix.os }}-${{ matrix.arch }} Native Binary"
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu
            runner: ubuntu-latest
            arch: x86_64
            output_name: npl-cli-linux-x86_64
          - os: ubuntu
            runner: linux-arm-64
            arch: aarch64
            output_name: npl-cli-linux-aarch64
          - os: macos
            runner: macos-13
            arch: x86_64
            output_name: npl-cli-macos-x86_64
          - os: macos
            runner: macos-latest
            arch: aarch64
            output_name: npl-cli-macos-aarch64

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Set up Maven"
        uses: actions/setup-java@v4
        with:
          distribution: "graalvm"
          java-version: "21"
          cache: "maven"

      - name: "Build npl-cli native binary and test it"
        run: mvn -Pnative clean verify
