name: "Verify and test"
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    name: "Run tests"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Set up Java and Maven"
        uses: actions/setup-java@v4
        with:
          distribution: "graalvm"
          java-version: "21"
          cache: "maven"

      - name: "Validate native config diff"
        run: .github/scripts/validate-native-configs.sh

      - name: "Validate CLI version matches latest platform release"
        run: .github/scripts/validate-version.sh

      - name: "Validate cli tool"
        run: mvn -Pnative package -DskipTests

      - name: "Verify"
        run: "mvn clean verify"
